### ISSUE TITLE
Bearing Angle Incorrect

### ISSUE THREAD

**Issue by tylerburnham42** [MSU-BOREALIS/Antenna_Tracker#10]
The bearing formula is incorrect. The current code is missing a Longitude as the final number. I believe you are incorrect closing my pull request with the modified bearing formula.

Here is a gist with an example the current code vs the correct code. The current calculation is off by about a degree in most cases. The last three lines of the gist are the sample output.
https://gist.github.com/tylerburnham42/3a501b64935a792d40ea6bf71e2d583f

 This site was cited in the source code of the formula. Using the calculator at the top of the webpage I got the third number to compare the correct result. 
http://www.movable-type.co.uk/scripts/latlong.html

Here is a screenshot of the result from using the tool in the link above. 
http://imgur.com/vkL3JlK

Here is a screenshot of the correct formula from the website above. 
http://imgur.com/X73kFqE

Here is the rejected pull request with the change. - https://github.com/MSU-BOREALIS/Antenna_Tracker/pull/1

**Comment by MSGC-BOREALIS** [comment]
The bearing angle calculation has been corrected. Thanks for the catch.
