### ISSUE TITLE
Unable to get GPS location from Ground Station

### ISSUE THREAD

**Issue by markshancock** [MSU-BOREALIS/Antenna_Tracker#11]
Bug is in antenna_dualtracker_GUI_v4.1.py line 684
   calibration = int(temp_arduino[8])+int(temp_arduino[7])+int(temp_arduino[6])+int(temp_arduino[5])

It looks like the intent was to add the calibration values coming back from the BNO055 which would be temp_arduino[7] temp_arduino[8] temp_arduino[9] and temp_arduino[10]

Read more: http://eclipsedesign.proboards.com/thread/133/antenna-tracker-gps-location-arduino#ixzz4jW7eGwCE

**Comment by trevor-gahl** [comment]
Moved on to new code version. V4.1 is no longer in use.
