### ISSUE TITLE
Autofill Ports doesn't always work

### ISSUE THREAD

**Issue by irowebbn** [MSU-BOREALIS/Antenna_Tracker#12]
Frequently, I am unable to start the program from Sypder when I already have my Arduino and Maestro plugged in. When I select run, I encounter this error: `if eachList[1].find(“Arduino Uno”) != -1) or (each.pid == 67): index error: list index out of range:1`

If I unplug my devices and start, the GUI launches just fine, but I have to manually input the COM ports from Device manager. I can usually reproduce this error, but every once in a while, the program _does_ launch and the ports numbers are already filled in.

**Comment by trevor-gahl** [comment]
This code isn't designed to use spyder. You can launch it through command line or modify the launcher file.
