### ISSUE TITLE
PySide error

### ISSUE THREAD

**Issue by josePhoenix** [MSU-BOREALIS/Antenna_Tracker#2]
Second-hand report, here:

On a fresh install with Anaconda2 on 32-bit Windows, this error appears:

```
Traceback (most recent call last):
  File "antenna_dualtracker_gui.py", line 1007, in <module>
    mGui = MainWindow()
  File "antenna_dualtracker_gui.py", line 231, in __init__
    layout.addWidget(self.canvas)
TypeError: 'PySide.QtGui.QBoxLayout.addWidget' called with wrong argument types:
  PySide.QtGui.QBoxLayout.addWidget(FigureCanvasQTAgg)
Supported signatures:
  PySide.QtGui.QBoxLayout.addWidget(PySide.QtGui.QWidget, int = 0, PySide.QtCore.Qt.Alignment = 0)
```

To fix, the `matplotlib` imports and configuration at the beginning of `V6/antenna_dualtracker_GUI_v6.0.py` should be rearranged to appear in this order:

```python
import matplotlib
matplotlib.rcParams['backend.qt4'] = 'PySide'
matplotlib.use('Qt4Agg')

from matplotlib.figure import Figure
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
```

That order appears to ensure that `FigureCanvasQTAgg` will derive from `PySide.QtGui.QWidget` as desired.

**Comment by bionicistGM** [comment]
The way that I got around it was to change the setting in Spyder. Go to Tools --> Preferences --> Console --> External Modules -->Qt-python binding libraries to always use pyside.
